<?php
// xml_data.php
/***********************************************
* Created:            Nov 6, 2012 4:49:21 PM
* Last Modified:      Nov 6, 2012 4:49:21 PM
*
* [LEFT BLANK FOR PROGRAM DISCRIPTION]
*
* Mike Browne - phelandhu@gmail.com
***********************************************/
/*
/ <?xml version="1.0"?>
*/
$xml_data = <<<XML
<REQUEST>
<REFERRAL>
<STOREKEY>I5uHFVhfKGWpdXOr</STOREKEY>
<REFURL>http://www.fscbb.com</REFURL>
<IPADDRESS>98.160.229.122</IPADDRESS>
<TIERKEY>I5uHFVhfKGWpdXOr</TIERKEY>
<AFFID>southern</AFFID>
<SUBID>northern</SUBID>
<TEST>1</TEST>
</REFERRAL>
<CUSTOMER>
<PERSONAL>
<REQUESTEDAMOUNT>10000</REQUESTEDAMOUNT>
<SSN>111224444</SSN>
<DOB>01-04-1976</DOB>
<GENDER>M</GENDER>
<FIRSTNAME>Jonathan</FIRSTNAME>
<MIDDLEINITIAL>m</MIDDLEINITIAL>
<LASTNAME>Doever</LASTNAME>
<ADDRESS>1343 NE Webster</ADDRESS>
<ADDRESS2>1343 NE Webster</ADDRESS2>
<CITY>Portland</CITY>
<STATE>or</STATE>
<ZIP>97211</ZIP>
<HOMEPHONE>5032840599</HOMEPHONE>
<OTHERPHONE>503284059</OTHERPHONE>
<DLSTATE>OR</DLSTATE>
<DLNUMBER>5189376</DLNUMBER>
<CONTACTTIME>M</CONTACTTIME>
<LENGTHATRESIDENCE>3</LENGTHATRESIDENCE>
<RENTOROWN>O</RENTOROWN>
<ISMILITARY>1</ISMILITARY>
<ISCITIZEN>1</ISCITIZEN>
<OTHEROFFERS>0</OTHEROFFERS>
<EMAIL>Jonathan@ColumbiaOutdoorWear.gov</EMAIL>
</PERSONAL>
<EMPLOYMENT>
<INCOMETYPE>E</INCOMETYPE>
<PAYTYPE>p</PAYTYPE>
<EMPMONTHS>11</EMPMONTHS>
<EMPYEARS>6</EMPYEARS>
<EMPNAME>ColumbiaOutdoorWear</EMPNAME>
<EMPADDRESS>111 MAIN street </EMPADDRESS>
<EMPADDRESS2>112 MAIN street </EMPADDRESS2>
<EMPCITY>Portland</EMPCITY>
<EMPSTATE>OR</EMPSTATE>
<EMPZIP>97211</EMPZIP>
<EMPPHONE>5035551212</EMPPHONE>
<EMPPHONEEXT>312</EMPPHONEEXT>
<EMPFAX>5035551214</EMPFAX>
<SUPERVISORNAME>Kyle</SUPERVISORNAME>
<SUPERVISORPHONE>5035551212</SUPERVISORPHONE>
<SUPERVISORPHONEEXT>110</SUPERVISORPHONEEXT>
<HIREDATE>07-29-2010</HIREDATE>
<EMPTYPE>F</EMPTYPE>
<JOBTITLE>Sales</JOBTITLE>
<WORKSHIFT>S</WORKSHIFT>
<PAYFREQUENCY>B</PAYFREQUENCY>
<NETMONTHLY>1012</NETMONTHLY>
<GROSSMONTHLY>1308</GROSSMONTHLY>
<LASTPAYDATE>07-29-2012</LASTPAYDATE>
<NEXTPAYDATE>07-13-2012</NEXTPAYDATE>
<SECONDPAYDATE>07-27-2012</SECONDPAYDATE>
</EMPLOYMENT>
<BANK>
<ACCOUNTHOLDER>Johnathan Doever</ACCOUNTHOLDER>
<BANKNAME>First Interstate</BANKNAME>
<BANKPHONE>5035551111</BANKPHONE>
<ACCOUNTTYPE>C</ACCOUNTTYPE>
<ROUTINGNUMBER>838583746</ROUTINGNUMBER>
<ACCOUNTNUMBER>09290048000000011</ACCOUNTNUMBER>
<LENGTHBANKING>0</LENGTHBANKING>
<OUTSTANDINGAMT>0</OUTSTANDINGAMT>
<ACTIVECHECKING>Y</ACTIVECHECKING>
</BANK>
<REFERENCES>
<REFERENCE>
<FIRSTNAME></FIRSTNAME>
<LASTNAME></LASTNAME>
<PHONE></PHONE>
<RELATIONSHIP></RELATIONSHIP>
</REFERENCE>
<REFERENCE>
<FIRSTNAME>Jane</FIRSTNAME>
<LASTNAME>Doever</LASTNAME>
<PHONE>5032840591</PHONE>
<RELATIONSHIP>S</RELATIONSHIP>
</REFERENCE>
<REFERENCE>
<FIRSTNAME></FIRSTNAME>
<LASTNAME></LASTNAME>
<PHONE></PHONE>
<RELATIONSHIP></RELATIONSHIP>
</REFERENCE>
</REFERENCES>
</CUSTOMER>
</REQUEST>
XML;
